name: Java CI with Gradle

on:
  push:
    branches: [ '*' ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build jacocoTestReport
    - name: Upload JaCoCo Coverage Report as a workflow artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jacoco-report-${{ matrix.os }}
        path: build/reports/jacoco/test/html/
    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib-${{ matrix.os }}.jar
        path: build/libs/*.jar
  
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Static Code Analysis
      run: ./gradlew check
    - name: Upload Checkstyle Report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: build/reports/checkstyle
  
  asset-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Check Asset Integrity
      run: |
        find ./assets -type f -exec file {} \;
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
    - name: Prepare Artifacts for Release
      run: |
        mv artifacts/lib-ubuntu-latest.jar lib-ubuntu.jar
        mv artifacts/lib-macos-latest.jar lib-macos.jar
        mv artifacts/lib-windows-latest.jar lib-windows.jar
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          lib-ubuntu.jar
          lib-macos.jar
          lib-windows.jar