name: Java CI with Gradle

on:
  push:
    branches: [ '*' ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build jacocoTestReport
    - name: Upload JaCoCo Coverage Report as a workflow artifact
      uses: actions/upload-artifact@vv4.3.1
      with:
        name: jacoco-report-${{ matrix.os }}
        path: build/reports/jacoco/test/html/
    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib-${{ matrix.os }}.jar
        path: build/libs/*.jar