name: Comprehensive CI Workflow

on:
  push:
    branches: [ '*' ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build test
    - name: Run Tests
      run: ./gradlew test
      working-directory: assets
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report-${{ matrix.os }}
        path: build/reports/jacoco/test/html/
    - name: Upload JAR Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib-${{ matrix.os }}.jar
        path: build/libs/*.jar
